# Tensor
A tensor is a multi-dimensional array (like a matrix) and a fundamental data structure in TensorFlow. It’s designed to handle high-dimensional data and operations on that data, much like vectors and matrices in linear algebra.

# Ranks
Rank refers to the number of dimensions in a tensor. A scalar (single value) has rank 0, a vector (1D array) has rank 1, a matrix (2D array) has rank 2, and so on.

__Example of ranks:__
- Rank 0 (Scalar): 1
- Rank 1 (Vector): [1, 2, 3]
- Rank 2 (Matrix): [[1, 2, 3], [4, 5, 6]]
- Rank 3 (3D Tensor): [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [1]:
import tensorflow as tf

# Rank 0 tensor (scalar)
scalar = tf.constant(5)

# Rank 1 tensor (vector)
vector = tf.constant([5, 6, 7])

# Rank 2 tensor (matrix)
matrix = tf.constant([[5, 6, 7], [8, 9, 10]])

# Rank 3 tensor
tensor_3d = tf.constant([[[5, 6], [7, 8]], [[9, 10], [11, 12]]])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:", matrix)
print("3D Tensor:", tensor_3d)

Scalar: tf.Tensor(5, shape=(), dtype=int32)
Vector: tf.Tensor([5 6 7], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[ 5  6  7]
 [ 8  9 10]], shape=(2, 3), dtype=int32)
3D Tensor: tf.Tensor(
[[[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(2, 2, 2), dtype=int32)


- __Shape__ describes the number of elements in each dimension of the tensor. For example, a tensor with shape `[2, 3]` has 2 rows and 3 columns.

   ```python
    print("Shape of Matrix:", matrix.shape)         # Shape: (2, 3)
    ```
<br/>

- Tensors can hold data in __different types__: integers (`tf.int32`, `tf.int64`), floating points (`tf.float32`, `tf.float64`), strings, etc.

  ```python
    float_tensor = tf.constant([1, 2, 3], dtype=tf.float32)
    print("Float Tensor:", float_tensor, "Type:", float_tensor.dtype)
    ```
<br/>

- TensorFlow supports various tensor __operations__, like
    - Addition: `tf.add`
    - Multiplication: `tf.multiply`
    - Matrix Multiplication: `tf.matmul`

In [9]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

add_result = tf.add(a, b)
multiply_result = tf.multiply(a, b)
matmul_result = tf.matmul(a, b)
div_result = tf.divide(a, b)

sum_result = tf.reduce_sum(a)
mean_result = tf.reduce_mean(a)
max_result = tf.reduce_max(a)
min_result = tf.reduce_min(a)

print("Element-wise Addition:\n", add_result)
print("Element-wise Multiplication:\n", multiply_result)
print("Matrix Multiplication:\n", matmul_result)
print("Division:", div_result)

print("Sum:", sum_result)             
print("Mean:", mean_result)           
print("Max:", max_result)             
print("Min:", min_result)

Element-wise Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Element-wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Division: tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)
Sum: tf.Tensor(10, shape=(), dtype=int32)
Mean: tf.Tensor(2, shape=(), dtype=int32)
Max: tf.Tensor(4, shape=(), dtype=int32)
Min: tf.Tensor(1, shape=(), dtype=int32)


In [14]:
import tensorflow as tf

# Define tensors with float data type
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Element-wise operations
add_result = tf.add(a, b)
multiply_result = tf.multiply(a, b)
div_result = tf.divide(a, b)

# Matrix multiplication
matmul_result = tf.matmul(a, b)

# Aggregation operations
sum_result = tf.reduce_sum(a)
mean_result = tf.reduce_mean(a)
max_result = tf.reduce_max(a)
min_result = tf.reduce_min(a)

# Exponentiation and square root
exp_result = tf.exp(a)
sqrt_result = tf.sqrt(a)

# Print results
print("Element-wise Addition:\n", add_result)
print("Element-wise Multiplication:\n", multiply_result)
print("Matrix Multiplication:\n", matmul_result)
print("Division:\n", div_result)

print("Sum:", sum_result)             
print("Mean:", mean_result)           
print("Max:", max_result)             
print("Min:", min_result)

print("Exponentiation:\n", exp_result)
print("Square Root:\n", sqrt_result)

Element-wise Addition:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Element-wise Multiplication:
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
Matrix Multiplication:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
Division:
 tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
Sum: tf.Tensor(10.0, shape=(), dtype=float32)
Mean: tf.Tensor(2.5, shape=(), dtype=float32)
Max: tf.Tensor(4.0, shape=(), dtype=float32)
Min: tf.Tensor(1.0, shape=(), dtype=float32)
Exponentiation:
 tf.Tensor(
[[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]], shape=(2, 2), dtype=float32)
Square Root:
 tf.Tensor(
[[1.        1.4142135]
 [1.7320508 2.       ]], shape=(2, 2), dtype=float32)
