# Tensor
A tensor is a multi-dimensional array (like a matrix) and a fundamental data structure in TensorFlow. It’s designed to handle high-dimensional data and operations on that data, much like vectors and matrices in linear algebra.

## Ranks
Rank refers to the number of dimensions in a tensor. A scalar (single value) has rank 0, a vector (1D array) has rank 1, a matrix (2D array) has rank 2, and so on.

__Example of ranks:__
- Rank 0 (Scalar): 1
- Rank 1 (Vector): [1, 2, 3]
- Rank 2 (Matrix): [[1, 2, 3], [4, 5, 6]]
- Rank 3 (3D Tensor): [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [1]:
import tensorflow as tf

# Rank 0 tensor (scalar)
scalar = tf.constant(5)

# Rank 1 tensor (vector)
vector = tf.constant([5, 6, 7])

# Rank 2 tensor (matrix)
matrix = tf.constant([[5, 6, 7], [8, 9, 10]])

# Rank 3 tensor
tensor_3d = tf.constant([[[5, 6], [7, 8]], [[9, 10], [11, 12]]])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:", matrix)
print("3D Tensor:", tensor_3d)

Scalar: tf.Tensor(5, shape=(), dtype=int32)
Vector: tf.Tensor([5 6 7], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[ 5  6  7]
 [ 8  9 10]], shape=(2, 3), dtype=int32)
3D Tensor: tf.Tensor(
[[[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(2, 2, 2), dtype=int32)


- __Shape__ describes the number of elements in each dimension of the tensor. For example, a tensor with shape `[2, 3]` has 2 rows and 3 columns.

   ```python
    print("Shape of Matrix:", matrix.shape)         # Shape: (2, 3)
    ```
<br/>

- Tensors can hold data in __different types__: integers (`tf.int32`, `tf.int64`), floating points (`tf.float32`, `tf.float64`), strings, etc.

  ```python
    float_tensor = tf.constant([1, 2, 3], dtype=tf.float32)
    print("Float Tensor:", float_tensor, "Type:", float_tensor.dtype)
    ```
<br/>

- TensorFlow supports various tensor __operations__, like
    - Addition: `tf.add`
    - Multiplication: `tf.multiply`
    - Matrix Multiplication: `tf.matmul`

In [2]:
import tensorflow as tf

# Define tensors with float data type
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Element-wise operations
add_result = tf.add(a, b)
multiply_result = tf.multiply(a, b)
div_result = tf.divide(a, b)

# Matrix multiplication
matmul_result = tf.matmul(a, b)

# Aggregation operations
sum_result = tf.reduce_sum(a)
mean_result = tf.reduce_mean(a)
max_result = tf.reduce_max(a)
min_result = tf.reduce_min(a)

# Exponentiation and square root
exp_result = tf.exp(a)
sqrt_result = tf.sqrt(a)

# Print results
print("Element-wise Addition:\n", add_result)
print("Element-wise Multiplication:\n", multiply_result)
print("Matrix Multiplication:\n", matmul_result)
print("Division:\n", div_result)

print("Sum:", sum_result)             
print("Mean:", mean_result)           
print("Max:", max_result)             
print("Min:", min_result)

print("Exponentiation:\n", exp_result)
print("Square Root:\n", sqrt_result)

Element-wise Addition:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Element-wise Multiplication:
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
Matrix Multiplication:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
Division:
 tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
Sum: tf.Tensor(10.0, shape=(), dtype=float32)
Mean: tf.Tensor(2.5, shape=(), dtype=float32)
Max: tf.Tensor(4.0, shape=(), dtype=float32)
Min: tf.Tensor(1.0, shape=(), dtype=float32)
Exponentiation:
 tf.Tensor(
[[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]], shape=(2, 2), dtype=float32)
Square Root:
 tf.Tensor(
[[1.        1.4142135]
 [1.7320508 2.       ]], shape=(2, 2), dtype=float32)


## `tf.data.Dataset` API
It is a powerful tool for building input pipelines to handle large datasets efficiently. It simplifies the process of loading, preprocessing, and iterating over data, making it ideal for preparing data for machine learning models, especially when working with large and complex datasets.

### Key Concepts
1. **Data Representation**:
    - The `Dataset` API represents a sequence of data elements, where each element consists of one or more components. Components can be single values, vectors, or even complex data structures like images and labels.
    - This API allows users to create datasets from arrays, files, or generators and transform them with functions that prepare the data for machine learning models.

2. **Creating a Dataset**:
    - You can create datasets from different sources such as in-memory data (e.g., lists, arrays), TFRecord files, or text files.
    - The `Dataset.from_tensor_slices()` method is commonly used to create datasets from in-memory data, such as lists or NumPy arrays.

3. **Transformations**: The API provides various transformations to process data efficiently, such as
    - `map()`: Apply a function to each element in the dataset.
    - `batch()`: Combines consecutive elements into batches, enabling mini-batch processing.
    - `shuffle()`: Randomly shuffles the data to improve model training and reduce overfitting.
    - `repeat()`: Repeats the dataset multiple times, useful for training over multiple epochs.
    
4. **Optimizing Pipelines**:
    - The API includes optimizations like prefetching, parallel mapping, and caching.
    - `prefetch()` helps overlap data preparation with model training by fetching the next -batch while the current batch is being processed.
    - `cache()` can store the dataset in memory after the first epoch, speeding up subsequent epochs.

5. **Iteration**: A `tf.data.Dataset` object is iterable, allowing you to loop through it directly or retrieve individual batches in a session or eager execution.

In [3]:
import tensorflow as tf
import numpy as np

# Sample data: features (inputs) and labels (targets)
features = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]], dtype=np.float32)
labels = np.array([0, 1, 0, 1], dtype=np.int32)

# Step 1: Create a Dataset
dataset = tf.data.Dataset.from_tensor_slices((features, labels))

# Step 2: Shuffle, Batch, and Repeat
batch_size = 2
dataset = dataset.shuffle(buffer_size=4).batch(batch_size).repeat(2)  # Shuffle, batch, and repeat

# Step 3: Map Transformation (Optional)
# Apply a simple map transformation to add noise to features (e.g., for data augmentation)
def add_noise(features, labels):
    noise = tf.random.normal(shape=tf.shape(features), mean=0.0, stddev=0.1)
    features = features + noise
    return features, labels

dataset = dataset.map(add_noise)

# Step 4: Prefetch for Optimized Performance
dataset = dataset.prefetch(buffer_size=tf.data.AUTOTUNE)

# Step 5: Iterate over the Dataset
for batch in dataset:
    print("Features:", batch[0].numpy())
    print("Labels:", batch[1].numpy())

Features: [[2.8997488 3.859724 ]
 [4.8605475 6.011254 ]]
Labels: [1 0]
Features: [[7.075528   7.8318596 ]
 [0.91776663 1.8035622 ]]
Labels: [1 0]
Features: [[5.1282496 6.0109253]
 [3.060341  3.939802 ]]
Labels: [0 1]
Features: [[6.930897  7.861804 ]
 [1.2034491 2.0419757]]
Labels: [1 0]


# Building and Training Models with Keras API
## Sequential API
The `Sequential` API in Keras is an easy and intuitive way to build and train simple neural network models layer by layer. This API is ideal for models that consist of a single input and a single output and follow a linear stack of layers.
### Key Concepts
1. **Sequential Model**:
    - The `Sequential` model is a linear stack of layers that are added one after another.
    - It is particularly useful for straightforward models like feedforward neural networks (dense layers) and simple convolutional or recurrent layers.
2. Layer Stacking:
    - You define the model by stacking different types of layers in the order you want them to execute.
    - Layers include Dense (fully connected layers), Conv2D (convolutional layers), Flatten, Dropout, and more.
3. **Compilation**:
    - After defining the layers, you compile the model to configure the learning process. This involves setting the optimizer, loss function, and metrics.
    - The optimizer (e.g., `adam`, `sgd`) controls how the model learns.
    - The loss function (e.g., `binary_crossentropy`, `mean_squared_error`) measures the model’s error and guides the training.
    - Metrics (e.g., `accuracy`) are used to evaluate the model’s performance.
4. **Training the Model**:
    - After compiling, the model can be trained on data using the `fit()` method. This involves passing the input data, target labels, batch size, and number of epochs.
    - During training, the model optimizes its weights to reduce the loss function value.
5. **Evaluation and Prediction**:
    - Once trained, the model’s performance can be evaluated on a test set using `evaluate()`.
    - Predictions for new data can be made using `predict()`.

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Step 1: Define a Sequential Model
model = Sequential([
    Dense(16, activation='relu', input_shape=(2,)),  # Input layer with 2 features, 16 neurons, ReLU activation
    Dense(8, activation='relu'),                     # Hidden layer with 8 neurons, ReLU activation
    Dense(1, activation='sigmoid')                   # Output layer with 1 neuron, Sigmoid activation for binary classification
])

# Step 2: Compile the Model
model.compile(optimizer='adam',                     # Adam optimizer
              loss='binary_crossentropy',           # Binary cross-entropy loss for binary classification
              metrics=['accuracy'])                 # Metric to monitor accuracy during training

# Sample training data (2D points)
import numpy as np
X_train = np.array([[0, 0], [1, 1], [1, 0], [0, 1]])
y_train = np.array([0, 0, 1, 1])

# Step 3: Train the Model
history = model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=0)  # Training the model for 100 epochs

# Step 4: Evaluate the Model
loss, accuracy = model.evaluate(X_train, y_train, verbose=0)
print("Training Loss:", loss)
print("Training Accuracy:", accuracy)

# Step 5: Make Predictions
predictions = model.predict(X_train)
print("Predictions:", predictions)

C:\Python\Python3.11\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Training Loss: 0.5280570983886719
Training Accuracy: 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step
Predictions: [[0.4936982 ]
 [0.41783324]
 [0.8179251 ]
 [0.50176513]]
